# Generated by Django 5.0 on 2025-07-22 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_book_book_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2025, 7, 22, 11, 29, 52, 32916, tzinfo=datetime.timezone.utc)),
        ),
    ]
